--- # Poggit-CI Manifest. Open the CI at projects:
projects:
  pocket-eloquent:
    type: library
    model: virion
    path: pocket-eloquent
    libs:
      - src: JackNoordhuis/framework/database
        version: 5.6.5
      - src: JackNoordhuis/framework/support
        version: 5.6.5
  ReturningPlayer:
    path: examples/ReturningPlayer
    libs:
      - src: JackNoordhuis/Pocket-Eloquent/pocket-eloquent
        version: 0.0.1
...
