--- # Poggit-CI Manifest. Open the CI at projects:
projects:
  pocket-eloquent:
    type: library
    model: virion
    path: pocket-eloquent
  ReturningPlayer:
    path: examples/ReturningPlayer
    libs:
      - src: /pocket-eloquent
        version: 0.0.1
...
