--- # Poggit-CI Manifest. Open the CI at projects:
projects:
  pocket-eloquent:
    type: library
    model: virion
    path: pocket-eloquent
    libs:
      - src: JackNoordhuis/Pocket-Eloquent/pocket-eloquent
        version: 1.22.1
  ReturningPlayer:
    path: examples/ReturningPlayer
    libs:
      - src: /pocket-eloquent
        version: 0.0.1
...
